# -*- mode: ruby -*-
# vi: set ft=ruby :

$copy_public_key = <<MARKUP
su -l ceph -c 'echo -e "\n\n" | ssh-keygen'
MARKUP
 
Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/trusty64"
 config.ssh.forward_agent = true
 config.ssh.insert_key = false
 config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
 
 config.vm.define "ceph-admin" do |admin|
  admin.vm.network :private_network, ip: "192.168.245.10"
  admin.vm.hostname = 'ceph-admin'
  admin.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf; domainname ceph-admin.local", privileged: true
  admin.vm.provision "shell", inline: "echo -e '192.168.245.10 ceph-admin\n192.168.245.11 ceph-client\n192.168.245.12 ceph-server-12\n192.168.245.13 ceph-server-13\n192.168.245.14 ceph-server-14' >>/etc/hosts", privileged: true
  admin.vm.provision "shell", inline: "useradd ceph && echo 'ceph\nceph' | passwd ceph && adduser ceph sudo && mkdir -p /home/ceph/.ssh && chown -R ceph:ceph /home/ceph", privileged: true
  admin.vm.provision "shell", inline: "wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -", privileged: true
  admin.vm.provision "shell", inline: "echo deb http://ceph.com/debian-firefly/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list", privileged: true
  admin.vm.provision "shell", inline: "apt-get -y update && sudo apt-get -y install ceph-deploy ntp openssh-server", privileged: true
  admin.vm.provision "shell", inline: "echo 'ceph ALL = (root) NOPASSWD:ALL' | tee /etc/sudoers.d/ceph", privileged: true 
  admin.vm.provision "shell", inline: "chmod 0440 /etc/sudoers.d/ceph && echo 'Defaults:ceph !requiretty' >> /etc/sudoers.d/ceph", privileged: true
  admin.vm.provision "shell", :inline => $copy_public_key
 end
 
 config.vm.define "ceph-client" do |client|
  client.vm.network :private_network, ip: "192.168.245.11"
  client.vm.hostname = 'ceph-client'
  client.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf; domainname ceph-client.local", privileged: true
  client.vm.provision "shell", inline: "echo -e '192.168.245.10 ceph-admin\n192.168.245.11 ceph-client\n192.168.245.12 ceph-server-12\n192.168.245.13 ceph-server-13\n192.168.245.14 ceph-server-14' >>/etc/hosts", privileged: true
  client.vm.provision "shell", inline: "useradd ceph && echo 'ceph\nceph' | passwd ceph && adduser ceph sudo && mkdir -p /home/ceph/.ssh && chown -R ceph:ceph /home/ceph", privileged: true
  client.vm.provision "shell", inline: "echo 'ceph ALL = (root) NOPASSWD:ALL' | tee /etc/sudoers.d/ceph", privileged: true 
  client.vm.provision "shell", inline: "chmod 0440 /etc/sudoers.d/ceph && echo 'Defaults:ceph !requiretty' >> /etc/sudoers.d/ceph", privileged: true
 end
 
 (1..3).each do |i|
  config.vm.define "ceph-server-#{i}" do |config|
  config.vm.network :private_network, ip: "192.168.245.#{i+11}"
  config.vm.hostname = "ceph-server-#{i}"
  config.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf; domainname ceph-server-#{i}.ceph.local"
  config.vm.provision "shell", inline: "echo -e '192.168.245.10 ceph-admin\n192.168.245.11 ceph-client\n192.168.245.12 ceph-server-12\n192.168.245.13 ceph-server-13\n192.168.245.14 ceph-server-14' >>/etc/hosts", privileged: true
  config.vm.provision "shell", inline: "useradd ceph && echo 'ceph\nceph' | passwd ceph && adduser ceph sudo && mkdir -p /home/ceph/.ssh && chown -R ceph:ceph /home/ceph", privileged: true
  config.vm.provision "shell", inline: "echo 'ceph ALL = (root) NOPASSWD:ALL' | tee /etc/sudoers.d/ceph", privileged: true 
  config.vm.provision "shell", inline: "chmod 0440 /etc/sudoers.d/ceph && echo 'Defaults:ceph !requiretty' >> /etc/sudoers.d/ceph", privileged: true
 end
 end
end
