# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
		config.vm.provider :aws do |aws, override|
			aws.access_key_id = "AKIAJBJO2LGVM2R7RJZA"
			aws.secret_access_key = "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"
			aws.keypair_name = "arkhangl"
			aws.instance_type = "t2.micro"
			aws.security_groups = ["basic"]
			aws.region = "us-west-2"
			aws.availability_zone = "us-west-2a"
			aws.ami = "ami-5189a661"
			override.ssh.username = "ubuntu"
			override.ssh.private_key_path = "~/.ssh/arkhangl.pem"
		end
		config.vm.define "itcook" do |itcook|
		itcook.vm.box = "amazon_base"
		itcook.vm.host_name = "itcook"
			itcook.vm.provision :salt do |salt|
			   salt.run_highstate = true
			   salt.minion_config = "./minion.conf"
			end
		end
end
